# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: "2"

services:

  orderer.coffeechain.com:
    container_name: orderer.coffeechain.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/coffeechain.com/orderers/orderer.coffeechain.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/coffeechain.com/orderers/orderer.coffeechain.com/tls/:/var/hyperledger/orderer/tls
        - orderer.coffeechain.com:/var/hyperledger/production/orderer.coffeechain.com
    ports:
      - 7050:7050

  peer0.cooperative.coffeechain.com:
    container_name: peer0.cooperative.coffeechain.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.cooperative.coffeechain.com
      - CORE_PEER_ADDRESS=peer0.cooperative.coffeechain.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.cooperative.coffeechain.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.cooperative.coffeechain.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.cooperative.coffeechain.com:7051
      - CORE_PEER_LOCALMSPID=CooperativeOrgMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/cooperative.coffeechain.com/peers/peer0.cooperative.coffeechain.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/cooperative.coffeechain.com/peers/peer0.cooperative.coffeechain.com/tls:/etc/hyperledger/fabric/tls
        - peer0.cooperative.coffeechain.com:/var/hyperledger/production
    ports:
      - 7051:7051

  peer1.cooperative.coffeechain.com:
    container_name: peer1.cooperative.coffeechain.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.cooperative.coffeechain.com
      - CORE_PEER_ADDRESS=peer1.cooperative.coffeechain.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.cooperative.coffeechain.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.cooperative.coffeechain.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.cooperative.coffeechain.com:7051
      - CORE_PEER_LOCALMSPID=CooperativeOrgMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/cooperative.coffeechain.com/peers/peer1.cooperative.coffeechain.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/cooperative.coffeechain.com/peers/peer1.cooperative.coffeechain.com/tls:/etc/hyperledger/fabric/tls
        - peer1.cooperative.coffeechain.com:/var/hyperledger/production

    ports:
      - 8051:8051

  peer0.transport.coffeechain.com:
    container_name: peer0.transport.coffeechain.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.transport.coffeechain.com
      - CORE_PEER_ADDRESS=peer0.transport.coffeechain.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.transport.coffeechain.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.transport.coffeechain.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.transport.coffeechain.com:10051
      - CORE_PEER_LOCALMSPID=TransportOrgMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/transport.coffeechain.com/peers/peer0.transport.coffeechain.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/transport.coffeechain.com/peers/peer0.transport.coffeechain.com/tls:/etc/hyperledger/fabric/tls
        - peer0.transport.coffeechain.com:/var/hyperledger/production
    ports:
      - 9051:9051

  peer1.transport.coffeechain.com:
    container_name: peer1.transport.coffeechain.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.transport.coffeechain.com
      - CORE_PEER_ADDRESS=peer1.transport.coffeechain.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer1.transport.coffeechain.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.transport.coffeechain.com:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.transport.coffeechain.com:9051
      - CORE_PEER_LOCALMSPID=TransportOrgMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/transport.coffeechain.com/peers/peer1.transport.coffeechain.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/transport.coffeechain.com/peers/peer1.transport.coffeechain.com/tls:/etc/hyperledger/fabric/tls
        - peer1.transport.coffeechain.com:/var/hyperledger/production
    ports:
      - 10051:10051

  peer0.insurance.coffeechain.com:
    container_name: peer0.insurance.coffeechain.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.insurance.coffeechain.com
      - CORE_PEER_ADDRESS=peer0.insurance.coffeechain.com:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer0.insurance.coffeechain.com:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.insurance.coffeechain.com:11051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.insurance.coffeechain.com:12051
      - CORE_PEER_LOCALMSPID=InsuranceOrgMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/insurance.coffeechain.com/peers/peer0.insurance.coffeechain.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/insurance.coffeechain.com/peers/peer0.insurance.coffeechain.com/tls:/etc/hyperledger/fabric/tls
        - peer0.insurance.coffeechain.com:/var/hyperledger/production
    ports:
      - 11051:11051

  peer1.insurance.coffeechain.com:
    container_name: peer1.insurance.coffeechain.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.insurance.coffeechain.com
      - CORE_PEER_ADDRESS=peer1.insurance.coffeechain.com:12051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:12051
      - CORE_PEER_CHAINCODEADDRESS=peer1.insurance.coffeechain.com:12052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:12052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.insurance.coffeechain.com:12051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.insurance.coffeechain.com:11051
      - CORE_PEER_LOCALMSPID=InsuranceOrgMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/insurance.coffeechain.com/peers/peer1.insurance.coffeechain.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/insurance.coffeechain.com/peers/peer1.insurance.coffeechain.com/tls:/etc/hyperledger/fabric/tls
        - peer1.insurance.coffeechain.com:/var/hyperledger/production
    ports:
      - 12051:12051


  peer0.miller.coffeechain.com:
    container_name: peer0.miller.coffeechain.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.miller.coffeechain.com
      - CORE_PEER_ADDRESS=peer0.miller.coffeechain.com:13051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:13051
      - CORE_PEER_CHAINCODEADDRESS=peer0.miller.coffeechain.com:13052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:13052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.miller.coffeechain.com:13051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.miller.coffeechain.com:14051
      - CORE_PEER_LOCALMSPID=MillerOrgMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/miller.coffeechain.com/peers/peer0.miller.coffeechain.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/miller.coffeechain.com/peers/peer0.miller.coffeechain.com/tls:/etc/hyperledger/fabric/tls
        - peer0.miller.coffeechain.com:/var/hyperledger/production
    ports:
      - 13051:13051

  peer1.miller.coffeechain.com:
    container_name: peer1.miller.coffeechain.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.miller.coffeechain.com
      - CORE_PEER_ADDRESS=peer1.miller.coffeechain.com:14051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:14051
      - CORE_PEER_CHAINCODEADDRESS=peer1.miller.coffeechain.com:14052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:14052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.miller.coffeechain.com:14051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.insurance.coffeechain.com:13051
      - CORE_PEER_LOCALMSPID=InsuranceOrgMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/miller.coffeechain.com/peers/peer1.miller.coffeechain.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/miller.coffeechain.com/peers/peer1.miller.coffeechain.com/tls:/etc/hyperledger/fabric/tls
        - peer1.miller.coffeechain.com:/var/hyperledger/production
    ports:
      - 14051:14051
